import { Product, Review, UserStats, InventoryStats, TrafficStats, ActivityStats } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: '1',
    title: 'MacBook Air M2 13"',
    description: 'Chip M2, 8GB RAM, 256GB SSD, Prateado. Estado de novo.',
    price: 6499.00,
    category: 'Eletrônicos',
    stock: 1,
    seller_id: 'seller1',
    is_active: true,
    rating: 4.9,
    units_sold: 12,
    images: ['https://images.unsplash.com/photo-1611186871348-b1ec696e52c9?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: '2023-12-01T10:00:00Z',
    updated_at: '2023-12-01T10:00:00Z'
  },
  {
    _id: '2',
    title: 'Fone de Ouvido Sony WH-1000XM5',
    description: 'Cancelamento de ruído líder da indústria, bateria de 30 horas.',
    price: 2100.00,
    category: 'Eletrônicos',
    stock: 5,
    seller_id: 'seller2',
    is_active: true,
    rating: 4.7,
    units_sold: 45,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: '2024-01-15T12:00:00Z',
    updated_at: '2024-01-15T12:00:00Z'
  },
  {
    _id: '3',
    title: 'Kindle Paperwhite 16GB',
    description: 'Tela de 6.8 polegadas, temperatura de luz ajustável.',
    price: 759.00,
    category: 'Livros',
    stock: 10,
    seller_id: 'seller1',
    is_active: true,
    rating: 4.8,
    units_sold: 120,
    images: ['https://images.unsplash.com/photo-1594980596277-536e4d9978ad?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: '2023-11-20T15:00:00Z',
    updated_at: '2023-11-20T15:00:00Z'
  },
  {
    _id: '4',
    title: 'Camiseta Algodão Egípcio',
    description: 'Conforto extremo e durabilidade. Diversas cores disponíveis.',
    price: 129.90,
    category: 'Vestuário',
    stock: 50,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '5',
    title: 'Cafeteira Expresso Italiana',
    description: 'Tradicional cafeteira Moka para 6 xícaras.',
    price: 189.00,
    category: 'Casa & Cozinha',
    stock: 15,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1544787210-2211d44b5057?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '6',
    title: 'Tênis Running Performance',
    description: 'Amortecimento responsivo para maratonas e treinos diários.',
    price: 549.00,
    category: 'Esportes',
    stock: 8,
    seller_id: 'seller4',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '7',
    title: 'Monitor 4K 27" Dell',
    description: 'Monitor profissional com fidelidade de cores e conexão USB-C.',
    price: 2899.00,
    category: 'Eletrônicos',
    stock: 3,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '8',
    title: 'Teclado Mecânico RGB',
    description: 'Switches blue, layout ABNT2, iluminação personalizável.',
    price: 350.00,
    category: 'Eletrônicos',
    stock: 12,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '9',
    title: 'Mochila Impermeável Tech',
    description: 'Compartimento para notebook até 15.6", porta USB externa.',
    price: 249.00,
    category: 'Vestuário',
    stock: 20,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '10',
    title: 'Luminária de Mesa LED',
    description: 'Ajuste de intensidade, base carregadora wireless.',
    price: 159.00,
    category: 'Casa & Cozinha',
    stock: 15,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '11',
    title: 'Câmera Mirrorless Canon',
    description: 'Sensor Full Frame, gravação em 4K, kit com lente 24-105mm.',
    price: 8900.00,
    category: 'Eletrônicos',
    stock: 2,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '12',
    title: 'Livro: O Código Limpo',
    description: 'Habilidades Práticas do Agile Software.',
    price: 85.00,
    category: 'Livros',
    stock: 30,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '13',
    title: 'Smartphone Galaxy S23',
    description: '128GB, 8GB RAM, Câmera Tripla 50MP.',
    price: 4200.00,
    category: 'Eletrônicos',
    stock: 6,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '14',
    title: 'Blazer Slim Fit Masculino',
    description: 'Corte moderno, tecido premium, ideal para eventos sociais.',
    price: 389.00,
    category: 'Vestuário',
    stock: 10,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '15',
    title: 'Air Fryer Digital 4L',
    description: 'Painel touch, cesto antiaderente, diversas funções pré-programadas.',
    price: 459.00,
    category: 'Casa & Cozinha',
    stock: 18,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1626071494702-4204c6e28732?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '16',
    title: 'Bicicleta Mountain Bike',
    description: 'Quadro em alumínio, 21 marchas, freio a disco.',
    price: 1599.00,
    category: 'Esportes',
    stock: 4,
    seller_id: 'seller4',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '17',
    title: 'Tablet iPad Pro 11"',
    description: 'M2, 128GB, Tela Liquid Retina.',
    price: 7800.00,
    category: 'Eletrônicos',
    stock: 3,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '18',
    title: 'Mouse Gamer Logitech',
    description: 'Sensor HERO 25K, iluminação LIGHTSYNC, 11 botões programáveis.',
    price: 299.00,
    category: 'Eletrônicos',
    stock: 15,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1527690191606-13a642b2f293?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '19',
    title: 'Jaqueta Jeans Oversized',
    description: 'Estilo street, lavagem estonada.',
    price: 199.00,
    category: 'Vestuário',
    stock: 12,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1550993012-70b9eb537b0d?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '20',
    title: 'Conjunto de Facas Chef',
    description: 'Aço inox de alta qualidade, 6 peças com suporte.',
    price: 320.00,
    category: 'Casa & Cozinha',
    stock: 7,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1593611666491-1ca90f3c5521?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '21',
    title: 'Smartwatch Apple Watch S8',
    description: 'Monitoramento de saúde, tela sempre ativa.',
    price: 3200.00,
    category: 'Eletrônicos',
    stock: 5,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1434493907317-a46b5bc78344?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '22',
    title: 'Quadro Decorativo Abstrato',
    description: 'Tela em canvas, moldura em madeira preta.',
    price: 145.00,
    category: 'Casa & Cozinha',
    stock: 10,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '23',
    title: 'Óculos de Sol Aviador',
    description: 'Lentes polarizadas, proteção UV400.',
    price: 280.00,
    category: 'Vestuário',
    stock: 15,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '24',
    title: 'Bola de Futebol Profissional',
    description: 'Aprovada pela FIFA, tecnologia sem costura.',
    price: 199.00,
    category: 'Esportes',
    stock: 25,
    seller_id: 'seller4',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1518005020250-eccdd5f1d954?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '25',
    title: 'Kit Yoga (Tapete + Blocos)',
    description: 'Tapete antiderrapante de 6mm, blocos de EVA.',
    price: 180.00,
    category: 'Esportes',
    stock: 10,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '26',
    title: 'Echo Dot 5ª Geração',
    description: 'Com Alexa e som superior.',
    price: 399.00,
    category: 'Eletrônicos',
    stock: 20,
    seller_id: 'seller2',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '27',
    title: 'Moletom Canguru Preto',
    description: 'Unissex, 100% algodão, macio e quente.',
    price: 159.00,
    category: 'Vestuário',
    stock: 40,
    seller_id: 'seller3',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    _id: '28',
    title: 'Aspirador de Pó Robô',
    description: 'Autônomo, sensor de queda, volta para a base.',
    price: 1200.00,
    category: 'Casa & Cozinha',
    stock: 5,
    seller_id: 'seller1',
    is_active: true,
    images: ['https://images.unsplash.com/photo-1622432924168-963f45811c75?auto=format&fit=crop&q=80&w=1000'],
    attributes: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    _id: 'r1',
    product_id: '1',
    user_id: 'user1',
    user_name: 'Marcos Silva',
    rating: 5,
    comment: 'Excelente produto, chegou muito rápido!',
    created_at: new Date().toISOString()
  },
  {
    _id: 'r2',
    product_id: '1',
    user_id: 'user2',
    user_name: 'Ana Costa',
    rating: 4,
    comment: 'Muito bom, mas o preço é um pouco alto.',
    created_at: new Date().toISOString()
  }
];

export const MOCK_ADMIN_STATS = {
  users: {
    total_users: 1542,
    total_orders: 867,
    total_transacted: 125430.50,
    avg_balance: 450.25
  } as UserStats,
  inventory: {
    total_products: 352,
    avg_rating: 4.65,
    zero_stock: 12,
    by_category: [
      { category: 'Eletrônicos', count: 124 },
      { category: 'Vestuário', count: 86 },
      { category: 'Casa', count: 42 },
      { category: 'Esportes', count: 65 },
      { category: 'Livros', count: 35 }
    ]
  } as InventoryStats,
  traffic: {
    active_carts: 56,
    cached_searches: 1240
  } as TrafficStats,
  activity: {
    last_views: [
      { user_id: 'usr_f89s', product_name: 'MacBook Air M2', price: 6499, viewed_at: new Date().toISOString() },
      { user_id: 'usr_a2d1', product_name: 'iPhone 15 Pro', price: 8499, viewed_at: new Date().toISOString() },
      { user_id: 'usr_c4e5', product_name: 'Kindle Paperwhite', price: 759, viewed_at: new Date().toISOString() },
      { user_id: 'usr_m7q2', product_name: 'Sony WH-1000XM5', price: 2100, viewed_at: new Date().toISOString() },
      { user_id: 'usr_p9l0', product_name: 'Monitor Dell 4K', price: 2899, viewed_at: new Date().toISOString() },
      { user_id: 'usr_z1x3', product_name: 'Teclado RGB', price: 350, viewed_at: new Date().toISOString() },
      { user_id: 'usr_h5n4', product_name: 'Jaqueta Jeans', price: 199, viewed_at: new Date().toISOString() },
      { user_id: 'usr_k8o2', product_name: 'Air Fryer 4L', price: 459, viewed_at: new Date().toISOString() },
      { user_id: 'usr_j6u1', product_name: 'Bicicleta MTB', price: 1599, viewed_at: new Date().toISOString() },
      { user_id: 'usr_r3t5', product_name: 'Câmera Canon', price: 8900, viewed_at: new Date().toISOString() },
    ],
    last_logins: [
      { user_id: 'usr_f89s', logged_at: new Date().toISOString(), ip_address: '172.16.254.1', device: 'Chrome / macOS' },
      { user_id: 'usr_a2d1', logged_at: new Date().toISOString(), ip_address: '189.12.45.67', device: 'Safari / iPhone' },
      { user_id: 'usr_m7q2', logged_at: new Date().toISOString(), ip_address: '200.45.1.23', device: 'Edge / Windows' },
      { user_id: 'usr_p9l0', logged_at: new Date().toISOString(), ip_address: '10.0.0.15', device: 'Firefox / Linux' },
      { user_id: 'usr_z1x3', logged_at: new Date().toISOString(), ip_address: '45.123.0.1', device: 'Chrome / Android' },
      { user_id: 'usr_h5n4', logged_at: new Date().toISOString(), ip_address: '191.1.2.3', device: 'Chrome / iOS' },
      { user_id: 'usr_c4e5', logged_at: new Date().toISOString(), ip_address: '8.8.8.8', device: 'Opera / macOS' },
      { user_id: 'usr_m7q2', logged_at: new Date().toISOString(), ip_address: '1.1.1.1', device: 'Brave / Windows' },
      { user_id: 'usr_k8o2', logged_at: new Date().toISOString(), ip_address: '127.0.0.1', device: 'Local / Node' },
      { user_id: 'usr_j6u1', logged_at: new Date().toISOString(), ip_address: '102.34.56.78', device: 'Vivaldi / Linux' },
    ],
    last_purchases: [
      { user_id: 'usr_f89s', product_name: 'MacBook Air M2', total: 6499, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_a2d1', product_name: 'Kindle Paperwhite', total: 759, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_m7q2', product_name: 'Sony WH-1000XM5', total: 4200, quantity: 2, purchased_at: new Date().toISOString() },
      { user_id: 'usr_p9l0', product_name: 'Monitor Dell 4K', total: 2899, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_z1x3', product_name: 'Teclado RGB', total: 350, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_h5n4', product_name: 'Jaqueta Jeans', total: 199, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_k8o2', product_name: 'Air Fryer 4L', total: 459, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_j6u1', product_name: 'Bicicleta MTB', total: 1599, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_r3t5', product_name: 'Câmera Canon', total: 8900, quantity: 1, purchased_at: new Date().toISOString() },
      { user_id: 'usr_c4e5', product_name: 'Luminária LED', total: 318, quantity: 2, purchased_at: new Date().toISOString() },
    ]
  } as ActivityStats
};

